### ISSUE TITLE
Getting unknown property when trying to open create article form

### ISSUE THREAD

**Issue by StickeydM** [cinghie/yii2-articles#4]
When I try to open a form of creating a article item using this URL `PathToApp/articles/items/create`  I get the next exception: 
`Getting unknown property: yii\web\UrlManager::languages.` 

items _form view tryes to get languages using the way below, but it can't do it:
`$select2languages = $model->getLanguagesSelect2();`

code in cinghie\articles\models\Articles model where it breaks:
```public function getLanguagesSelect2()
	{
		$languages = Yii::$app->urlManager->languages;        
                ...
	}```
Seems that categories _form view gets languages another way, and it works:
`$languages = Yii::$app->controller->module->languages;`

I think that it's not my problem and I don't understand why are you using 2 different ways to get the same variable. Am i wrong and made a mistake somewhere or it's your bug here?

**Comment by cinghie** [comment]
Hi StickeydM,

i'm changing the language system of this extension to work with [https://github.com/cinghie/yii2-multilanguage](https://github.com/cinghie/yii2-multilanguage) that is an extension of great [https://github.com/codemix/yii2-localeurls](https://github.com/codemix/yii2-localeurls).

I'm starting to changing the system from items but i don't finish it. In next days an update will complete the porting and my yii2-multilanguage will be required.

I suggest you to install the multilanguage extension to fix your problem and because all next versions of yii2-articles will use it.

**Comment by StickeydM** [comment]
Cinghie, yes, I can resolve this problem the way you offered, but what if my site will work only with one language? I don't need multilanguage support, do I really need to use this extension?

**Comment by client510** [comment]
Please tell me how to fix it? I'm constantly on the module error 403. Thank you.

**Comment by cinghie** [comment]
Last version fix the bug

I recommend to reload migrations because the field "published" was changed to "state" or change it manually on the database
